### PR TITLE
Create contrasts Dict directly

### PR DESCRIPTION
**Pull request by dmbates**
- Replace instances of `merge(Dict(...), Dict(...), ...)` with just `Dict(...)`.

### CODE REVIEW

**Comment by kliegl** [comment]
Much better.  We also used a loop sometimes for assigning the same contrast to multiple factors, but I think this can be left for an in-class demonstration.  Please go ahead and merge. Thanks!

**Review by palday — APPROVED** [review]

**Comment by kliegl** [comment]
By the way, I changed the names of Bahmanian files  - NumberAgreement --. This was a copy/paste error from a different participant.

**Comment by palday** [comment]
@dmbates I'll do a quick conflict resolution + render then merge

**Comment by dmbates** [comment]
> @dmbates I'll do a quick conflict resolution + render then merge

Thank you.  Please don't wait for me to do the merge.  These next few days are going to be very busy for me as my replacement computer is expected to be delivered tomorrow.  On the bright side that means that one of us will have experience configuring everything from scratch.

**Pull request merged**
